# AR overdue report upload and process

In [1]:
import pandas as pd

In [3]:
oddf=pd.read_excel("../major/static/temp/archeck.xlsx")

### The Dictionary: Translate the field names to eng names

In [7]:
od_fields=dict({
u'城市':"city",
u'客户编号':"cid",
u'客户名称':"cnm",
u'客户类型':"ctyp",
u'逾期天数':"oday",
u'账期':"term",
u'未核销金额':"amt",
u'下单日期':"odt",
u'发货日期':"ddt",
u'原始销售订单':"oodr",
u'销售订单':"odr",
u'销售订单金额':"oamt",
u'交货单':"dn",
u'开票日期':"idt",
u'手工发票号':"inv",
u'发票金额':"iamt",
u'发票抬头':"itt",
u'已核销金额':"aamt",
u'发票类型':"ityp",
u'付款方式':"pay",
})

In [6]:
oddf.columns

Index([u'城市', u'客户编号', u'客户名称', u'客户类型', u'逾期天数', u'账期', u'未核销金额', u'下单日期',
       u'发货日期', u'原始销售订单', u'销售订单', u'销售订单金额', u'交货单', u'开票日期', u'手工发票号',
       u'发票金额', u'发票抬头', u'已核销金额', u'发票类型', u'付款方式'],
      dtype='object')

In [8]:
oddf=oddf.rename(columns=od_fields)
oddf

,city,cid,cnm,ctyp,oday,term,amt,odt,ddt,oodr,odr,oamt,dn,idt,inv,iamt,itt,aamt,ityp,pay
0,SZ,1000257654,深圳市宝安区沙井人民医院,政府LARGE,657,开票30天,200.25,2015-05-15,2015-05-19,1001292,1001292,410.62,801079650,2015-05-18,12052989,410.62,深圳市宝安区沙井人民医院,210.37,普票,收款-转账
1,SZ,1000257654,深圳市宝安区沙井人民医院,政府LARGE,618,开票30天,1358.28,2015-05-15,2015-05-22,1001293,1001293,1358.28,801091405,2015-06-26,12056501,1358.28,深圳市宝安区沙井人民医院,0.00,普票,收款-转账
2,SZ,1000257654,深圳市宝安区沙井人民医院,政府LARGE,608,开票30天,33.84,2015-05-18,2015-05-19,1001701,1001701,33.84,801080246,2015-07-06,12057419,33.84,深圳市宝安区沙井人民医院,0.00,普票,收款-转账
3,SZ,1000257654,深圳市宝安区沙井人民医院,政府LARGE,608,开票30天,226.38,2015-05-18,2015-05-19,1001702,1001702,226.38,801080247,2015-07-06,12057419,226.38,深圳市宝安区沙井人民医院,0.00,普票,收款-转账
4,SZ,1000257654,深圳市宝安区沙井人民医院,政府LARGE,536,开票30天,1358.28,2015-05-18,2015-05-22,1001703,1001703,1358.28,801091406,2015-09-16,12064243,1358.28,深圳市宝安区沙井人民医院,0.00,普票,收款-转账
5,SZ,1000257654,深圳市宝安区沙井人民医院,政府LARGE,608,开票30天,1066.20,2015-05-18,2015-05-19,1004042,1004042,1066.20,801082000,2015-07-06,12057419,1066.20,深圳市宝安区沙井人民医院,0.00,普票,收款-转账
6,BJ,1000218365,外交部驻外机构供应处,政府LARGE,406,开票70天,1286.06,2015-05-19,2015-05-20,1006547,1006547,1286.06,801085130,2015-12-15,20609400,1286.06,外交部,0.00,普票,收款-转账
7,BJ,1000218365,外交部驻外机构供应处,政府LARGE,406,开票70天,3100.00,2015-05-19,2015-05-20,1006558,1006558,3100.00,801084470,2015-12-15,20609400,3100.00,外交部,0.00,普票,收款-转账
8,BJ,1000218365,外交部驻外机构供应处,政府LARGE,406,开票70天,786.52,2015-05-19,2015-05-20,1006614,1006614,786.52,801085131,2015-12-15,20609400,786.52,外交部,0.00,普票,收款-转账
9,BJ,1000218365,外交部驻外机构供应处,政府LARGE,406,开票70天,345.32,2015-05-19,2015-05-20,1006720,1006720,345.32,801085135,2015-12-15,20609400,345.32,外交部,0.00,普票,收款-转账
10,BJ,1000218365,外交部驻外机构供应处,政府LARGE,406,开票70天,198.00,2015-05-19,2015-05-26,1006722,1006722,198.00,801097025,2015-12-15,20609400,198.00,外交部,0.00,普票,收款-转账
11,BJ,1000218365,外交部驻外机构供应处,政府LARGE,406,开票70天,623.95,2015-05-19,2015-05-20,1006769,1006769,623.95,801085136,2015-12-15,20609400,623.95,外交部,0.00,普票,收款-转账
12,BJ,1000218365,外交部驻外机构供应处,政府LARGE,406,开票70天,268.75,2015-05-19,2015-05-20,1006817,1006817,268.75,801085137,2015-12-15,20609400,268.75,外交部,0.00,普票,收款-转账
13,BJ,1000218365,外交部驻外机构供应处,政府LARGE,406,开票70天,240.37,2015-05-19,2015-05-20,1006916,1006916,240.37,801085138,2015-12-15,20609400,240.37,外交部,0.00,普票,收款-转账
14,BJ,1000218365,外交部驻外机构供应处,政府LARGE,406,开票70天,680.00,2015-05-19,2015-05-20,1006997,1006997,680.00,801085127,2015-12-15,20609400,680.00,外交部,0.00,普票,收款-转账
15,BJ,1000218365,外交部驻外机构供应处,政府LARGE,406,开票70天,202.40,2015-05-19,2015-05-20,1007041,1007041,202.40,801085141,2015-12-15,20609400,202.40,外交部,0.00,普票,收款-转账
16,BJ,1000218365,外交部驻外机构供应处,政府LARGE,406,开票70天,99.92,2015-05-19,2015-05-20,1007059,1007059,99.92,801085144,2015-12-15,20609400,99.92,外交部,0.00,普票,收款-转账
17,BJ,1000218365,外交部驻外机构供应处,政府LARGE,406,开票70天,1142.00,2015-05-19,2015-05-20,1007100,1007100,1142.00,801085146,2015-12-15,20609400,1142.00,外交部,0.00,普票,收款-转账
18,BJ,1000218365,外交部驻外机构供应处,政府LARGE,406,开票70天,636.10,2015-05-19,2015-05-20,1007151,1007151,636.10,801085150,2015-12-15,20609400,636.10,外交部,0.00,普票,收款-转账
19,BJ,1000218365,外交部驻外机构供应处,政府LARGE,406,开票70天,6148.12,2015-05-19,2015-05-20,1007186,1007186,6148.12,801085151,2015-12-15,20609400,6148.12,外交部,0.00,普票,收款-转账
20,BJ,1000218365,外交部驻外机构供应处,政府LARGE,406,开票70天,1136.40,2015-05-19,2015-05-21,1007233,1007233,1136.40,801085154,2015-12-15,20609400,1136.40,外交部,0.00,普票,收款-转账
21,BJ,1000218365,外交部驻外机构供应处,政府LARGE,406,开票70天,1822.52,2015-05-19,2015-05-21,1007277,1007277,1822.52,801085156,2015-12-15,20609400,1822.52,外交部,0.00,普票,收款-转账
22,BJ,1000218365,外交部驻外机构供应处,政府LARGE,406,开票70天,41.60,2015-05-20,2015-05-21,1009240,1009240,41.60,801087572,2015-12-15,20609400,41.60,外交部,0.00,普票,收款-转账
23,BJ,1000218365,外交部驻外机构供应处,政府LARGE,406,开票70天,804.00,2015-05-20,2015-05-21,1009259,1009259,804.00,801087573,2015-12-15,20609400,804.00,外交部,0.00,普票,收款-转账
24,BJ,1000218365,外交部驻外机构供应处,政府LARGE,406,开票70天,246.90,2015-05-20,2015-05-21,1009268,1009268,246.90,801087574,2015-12-15,20609400,246.90,外交部,0.00,普票,收款-转账
25,NBJ,1000276761,中国科学院微电子研究所（政）(NBJ陈老师),政府MEDIUM,27,开票70天,126.00,2015-05-20,2015-05-22,1009888,1009888,666.00,801088622,2016-12-28,5436727,126.00,中国科学院微电子研究所,0.00,普票,收款-转账
26,NBJ,1000276761,中国科学院微电子研究所（政）(NBJ陈老师),政府MEDIUM,27,开票70天,540.00,2015-05-20,2015-05-22,1009888,1009888,666.00,801088622,2016-12-28,5436728,540.00,中国科学院微电子研究所,0.00,普票,收款-转账
27,BJ,1000218365,外交部驻外机构供应处,政府LARGE,406,开票70天,163.68,2015-05-20,2015-05-21,1009956,1009956,163.68,801088322,2015-12-15,20609400,163.68,外交部,0.00,普票,收款-转账
28,BJ,1000236974,海淀区八里庄街道办事处（杨月华）,政府AD-HOC,548,开票60天,185.00,2015-05-21,2015-05-22,1011092,1011092,185.00,801089913,2015-08-05,9136762,185.00,海淀区八里庄街道办事处,0.00,普票,收款-现金
29,BJ,1000218365,外交部驻外机构供应处,政府LARGE,406,开票70天,42.00,2015-05-26,2015-05-27,1021331,1021331,42.00,801100336,2015-12-15,20609400,42.00,外交部,0.00,普票,收款-转账
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1965,BJ,1000419719,安邦保险集团-黑龙江分公司,企业SBA-LARGE,137,开票70天,10.53,2016-06-28,2016-06-29,1953731,1953731,10.53,802116752,2016-09-09,48680,10.53,安邦财产保险股份有限公司黑龙江分公司,0.00,增票,收款-转账
1966,BJ,1000419719,安邦保险集团-黑龙江分公司,企业SBA-LARGE,137,开票70天,2.58,2016-06-28,2016-06-29,1953738,1953738,2.58,802116753,2016-09-09,48680,2.58,安邦财产保险股份有限公司黑龙江分公司,0.00,增票,收款-转账
1967,BJ,1000419719,安邦保险集团-黑龙江分公司,企业SBA-LARGE,137,开票70天,3.48,2016-06-28,2016-06-29,1953743,1953743,3.48,802116754,2016-09-09,48680,3.48,安邦财产保险股份有限公司黑龙江分公司,0.00,增票,收款-转账
1968,BJ,1000419719,安邦保险集团-黑龙江分公司,企业SBA-LARGE,137,开票70天,6.60,2016-06-28,2016-06-29,1953744,1953744,6.60,802116755,2016-09-09,48680,6.60,安邦财产保险股份有限公司黑龙江分公司,0.00,增票,收款-转账
1969,BJ,1000419719,安邦保险集团-黑龙江分公司,企业SBA-LARGE,137,开票70天,7.38,2016-06-28,2016-07-01,1953748,1953748,7.38,802124192,2016-09-09,48680,7.38,安邦财产保险股份有限公司黑龙江分公司,0.00,增票,收款-转账
1970,BJ,1000419719,安邦保险集团-黑龙江分公司,企业SBA-LARGE,137,开票70天,109.11,2016-06-28,2016-06-29,1953763,1953763,109.11,802116758,2016-09-09,48680,109.11,安邦财产保险股份有限公司黑龙江分公司,0.00,增票,收款-转账
1971,BJ,1000419719,安邦保险集团-黑龙江分公司,企业SBA-LARGE,137,开票70天,33.45,2016-06-28,2016-06-29,1953766,1953766,33.45,802116759,2016-09-09,48680,33.45,安邦财产保险股份有限公司黑龙江分公司,0.00,增票,收款-转账
1972,SH,1000427315,大唐桂冠合山发电有限公司,政府LARGE,146,开票70天,375.55,2016-06-28,2016-07-08,1954065,1954065,375.55,802144167,2016-08-31,21561763,375.55,中国水利电力物资集团有限公司东北分公司,0.00,增票,收款-转账
1973,BJ,1000419711,安邦保险集团-辽宁分公司,企业SBA-LARGE,137,开票70天,126.98,2016-06-29,2016-06-29,1954295,1954295,171.36,802117922,2016-09-09,48684,126.98,安邦财产保险股份有限公司辽宁分公司,0.00,增票,收款-转账
1974,BJ,1000419711,安邦保险集团-辽宁分公司,企业SBA-LARGE,137,开票70天,44.38,2016-06-29,2016-07-06,1954295,1954295,171.36,802142198,2016-09-09,48684,44.38,安邦财产保险股份有限公司辽宁分公司,0.00,增票,收款-转账
1975,BJ,1000419711,安邦保险集团-辽宁分公司,企业SBA-LARGE,137,开票70天,31.21,2016-06-29,2016-07-01,1954316,1954316,31.21,802125320,2016-09-09,48684,31.21,安邦财产保险股份有限公司辽宁分公司,0.00,增票,收款-转账
1976,BJ,1000419711,安邦保险集团-辽宁分公司,企业SBA-LARGE,137,开票70天,89.75,2016-06-29,2016-06-30,1954325,1954325,602.70,802117927,2016-09-09,48684,89.75,安邦财产保险股份有限公司辽宁分公司,0.00,增票,收款-转账
1977,BJ,1000419711,安邦保险集团-辽宁分公司,企业SBA-LARGE,137,开票70天,512.95,2016-06-29,2016-07-13,1954325,1954325,602.70,802164292,2016-09-09,48684,512.95,安邦财产保险股份有限公司辽宁分公司,0.00,增票,收款-转账
1978,SH,1000078332,上海第一机床厂有限公司（上海电气集团）,企业SEA-2,225,开票40天,625.50,2016-06-29,2016-06-30,1954331,1954331,625.50,802117818,2016-07-13,86549845,625.50,上海第一机床厂有限公司,0.00,增票,收款-现金
1979,BJ,1000419711,安邦保险集团-辽宁分公司,企业SBA-LARGE,137,开票70天,30.68,2016-06-29,2016-06-29,1954392,1954392,398.67,802117936,2016-09-09,48684,30.68,安邦财产保险股份有限公司辽宁分公司,0.00,增票,收款-转账
1980,BJ,1000419711,安邦保险集团-辽宁分公司,企业SBA-LARGE,137,开票70天,367.99,2016-06-29,2016-07-04,1954392,1954392,398.67,802131265,2016-09-09,48684,367.99,安邦财产保险股份有限公司辽宁分公司,0.00,增票,收款-转账
1981,BJ,1000419711,安邦保险集团-辽宁分公司,企业SBA-LARGE,137,开票70天,137.15,2016-06-29,2016-06-30,1954402,1954402,784.10,802117938,2016-09-09,48684,137.15,安邦财产保险股份有限公司辽宁分公司,0.00,增票,收款-转账
1982,BJ,1000419711,安邦保险集团-辽宁分公司,企业SBA-LARGE,137,开票70天,646.95,2016-06-29,2016-07-07,1954402,1954402,784.10,802146495,2016-09-09,48684,646.95,安邦财产保险股份有限公司辽宁分公司,0.00,增票,收款-转账
1983,BJ,1000419711,安邦保险集团-辽宁分公司,企业SBA-LARGE,137,开票70天,64.83,2016-06-29,2016-06-30,1954457,1954457,740.34,802117948,2016-09-09,48684,64.83,安邦财产保险股份有限公司辽宁分公司,0.00,增票,收款-转账
1984,BJ,1000419711,安邦保险集团-辽宁分公司,企业SBA-LARGE,137,开票70天,675.51,2016-06-29,2016-07-04,1954457,1954457,740.34,802131266,2016-09-09,48684,675.51,安邦财产保险股份有限公司辽宁分公司,0.00,增票,收款-转账
1985,BJ,1000419711,安邦保险集团-辽宁分公司,企业SBA-LARGE,137,开票70天,65.49,2016-06-29,2016-06-29,1954461,1954461,1102.04,802117950,2016-09-09,48684,65.49,安邦财产保险股份有限公司辽宁分公司,0.00,增票,收款-转账
1986,BJ,1000419711,安邦保险集团-辽宁分公司,企业SBA-LARGE,137,开票70天,1036.55,2016-06-29,2016-07-06,1954461,1954461,1102.04,802141424,2016-09-09,48684,1036.55,安邦财产保险股份有限公司辽宁分公司,0.00,增票,收款-转账
1987,BJ,1000419711,安邦保险集团-辽宁分公司,企业SBA-LARGE,137,开票70天,17.89,2016-06-29,2016-06-29,1954478,1954478,18.28,802117954,2016-09-09,48684,17.89,安邦财产保险股份有限公司辽宁分公司,0.00,增票,收款-转账
1988,BJ,1000419711,安邦保险集团-辽宁分公司,企业SBA-LARGE,137,开票70天,0.39,2016-06-29,2016-07-04,1954478,1954478,18.28,802131267,2016-09-09,48684,0.39,安邦财产保险股份有限公司辽宁分公司,0.00,增票,收款-转账
1989,BJ,1000419711,安邦保险集团-辽宁分公司,企业SBA-LARGE,137,开票70天,129.73,2016-06-29,2016-06-30,1954488,1954488,502.78,802117956,2016-09-09,48684,129.73,安邦财产保险股份有限公司辽宁分公司,0.00,增票,收款-转账
1990,BJ,1000419711,安邦保险集团-辽宁分公司,企业SBA-LARGE,137,开票70天,373.05,2016-06-29,2016-07-06,1954488,1954488,502.78,802141427,2016-09-09,48684,373.05,安邦财产保险股份有限公司辽宁分公司,0.00,增票,收款-转账
1991,BJ,1000419711,安邦保险集团-辽宁分公司,企业SBA-LARGE,137,开票70天,56.34,2016-06-29,2016-06-29,1954524,1954524,607.74,802117957,2016-09-09,48684,56.34,安邦财产保险股份有限公司辽宁分公司,0.00,增票,收款-转账
1992,BJ,1000419711,安邦保险集团-辽宁分公司,企业SBA-LARGE,137,开票70天,551.40,2016-06-29,2016-07-01,1954524,1954524,607.74,802124610,2016-09-09,48684,551.40,安邦财产保险股份有限公司辽宁分公司,0.00,增票,收款-转账
1993,SH,1000431213,北京国电通网络技术有限公司,政府SEA,188,开票85天,3776.00,2016-06-29,2016-07-05,1954756,1954756,3776.00,802132145,2016-07-05,86554958,3776.00,北京国电通网络技术有限公司,0.00,增票,收款-转账
1994,BJ,1000419742,安邦保险集团-杭州电销中心,企业SBA-LARGE,138,开票70天,850.07,2016-06-29,2016-06-30,1955456,1955456,850.07,802120636,2016-09-08,48616,850.07,安邦财产保险股份有限公司,0.00,增票,收款-转账

In [35]:
from datetime import date

In [61]:
rkeys=["city","amt","oamt","damt","odt","ddt","idt","odr","oodr","inv","dn","itt","cid"]
for rowid in range(len(oddf)):
    rd=oddf.loc[rowid].to_dict()
    rd2=dict()
    for k in rkeys:
        if rd.has_key(k):
            if k in ["amt","oamt","damt"]:# Process Number, float, and round to 2 decimal points
                rd2.update({k:round(rd[k],2)})
            elif k in ["cid","odr","oodr","dn","inv"]: #Process Serial Numbers
                rd2.update({k:str(rd[k])})
            elif k in ["odt","ddt","idt"]:#Process date format
                print(type(rd[k]))
                rd2.update({k:rd[k].to_datetime()})
            else:
                rd2.update({k:rd[k]})
    print rd2

<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
{'dn': '801079650', 'city': u'SZ', 'cid': '1000257654', 'odr': '1001292', 'oamt': 410.62, 'odt': datetime.datetime(2015, 5, 15, 0, 0), 'inv': '12052989', 'amt': 200.25, 'oodr': '1001292', 'itt': u'\u6df1\u5733\u5e02\u5b9d\u5b89\u533a\u6c99\u4e95\u4eba\u6c11\u533b\u9662', 'ddt': datetime.datetime(2015, 5, 19, 0, 0), 'idt': datetime.datetime(2015, 5, 18, 0, 0)}
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
{'dn': '801091405', 'city': u'SZ', 'cid': '1000257654', 'odr': '1001293', 'oamt': 1358.28, 'odt': datetime.datetime(2015, 5, 15, 0, 0), 'inv': '12056501', 'amt': 1358.28, 'oodr': '1001293', 'itt': u'\u6df1\u5733\u5e02\u5b9d\u5b89\u533a\u6c99\u4e95\u4eba\u6c11\u533b\u9662', 'ddt': datetime.datetime(2015, 5, 22, 0, 0), 'idt': datetime.datetime(2015, 6, 26, 0, 0)}
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
{'dn': '801080246', 'city': u'SZ', 'cid': '1000257654', 'odr': '1001701', 'oamt': 33.84, 'odt': datetime.datetime(2015, 5, 18, 0, 0), 'inv': '12057419', 'amt': 33.84, 'oodr': '1001701', 'itt': u'\u6df1\u5733\u5e02\u5b9d\u5b89\u533a\u6c99\u4e95\u4eba\u6c11\u533b\u9662', 'ddt': datetime.datetime(2015, 5, 19, 0, 0), 'idt': datetime.datetime(2015, 7, 6, 0, 0)}
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
{'dn': '801080247', 'city': u'SZ', 'cid': '1000257654', 'odr': '1001702', 'oamt': 226.38, 'odt': datetime.datetime(2015, 5, 18, 0, 0), 'inv': '12057419', 'amt': 226.38, 'oodr': '1001702', 'itt': u'\u6df1\u5733\u5e02\u5b9d\u5b89\u533a\u6c99\u4e95\u4eba\u6c11\u533b\u9662', 'ddt': datetime.datetime(2015, 5, 19, 0, 0), 'idt': datetime.datetime(2015, 7, 6, 0, 0)}
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
{'dn': '801091406', 'city': u'SZ', 'cid': '1000257654', 'odr': '1001703', 'oamt': 1358.28, 'odt': datetime.datetime(2015, 5, 18, 0, 0), 'inv': '12064243', 'amt': 1358.28, 'oodr': '1001703', 'itt': u'\u6df1\u5733\u5e02\u5b9d\u5b89\u533a\u6c99\u4e95\u4eba\u6c11\u533b\u9662', 'ddt': datetime.datetime(2015, 5, 22, 0, 0), 'idt': datetime.datetime(2015, 9, 16, 0, 0)}
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
{'dn': '801082000', 'city': u'SZ', 'cid': '1000257654', 'odr': '1004042', 'oamt': 1066.2, 'odt': datetime.datetime(2015, 5, 18, 0, 0), 'inv': '12057419', 'amt': 1066.2, 'oodr': '1004042', 'itt': u'\u6df1\u5733\u5e02\u5b9d\u5b89\u533a\u6c99\u4e95\u4eba\u6c11\u533b\u9662', 'ddt': datetime.datetime(2015, 5, 19, 0, 0), 'idt': datetime.datetime(2015, 7, 6, 0, 0)}
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
{'dn': '801085130', 'city': u'BJ', 'cid': '1000218365', 'odr': '1006547', 'oamt': 1286.06, 'odt': datetime.datetime(2015, 5, 19, 0, 0), 'inv': '20609400', 'amt': 1286.06, 'oodr': '1006547', 'itt': u'\u5916\u4ea4\u90e8', 'ddt': datetime.datetime(2015, 5, 20, 0, 0), 'idt': datetime.datetime(2015, 12, 15, 0, 0)}
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
{'dn': '801084470', 'city': u'BJ', 'cid': '1000218365', 'odr': '1006558', 'oamt': 3100.0, 'odt': datetime.datetime(2015, 5, 19, 0, 0), 'inv': '20609400', 'amt': 3100.0, 'oodr': '1006558', 'itt': u'\u5916\u4ea4\u90e8', 'ddt': datetime.datetime(2015, 5, 20, 0, 0), 'idt': datetime.datetime(2015, 12, 15, 0, 0)}
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
{'dn': '801085131', 'city': u'BJ', 'cid': '1000218365', 'odr': '1006614', 'oamt': 786.52, 'odt': datetime.datetime(2015, 5, 19, 0, 0), 'inv': '20609400', 'amt': 786.52, 'oodr': '1006614', 'itt': u'\u5916\u4ea4\u90e8', 'ddt': datetime.datetime(2015, 5, 20, 0, 0), 'idt': datetime.datetime(2015, 12, 15, 0, 0)}
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
{'dn': '801085135', 'city': u'BJ', 'cid': '1000218365', 'odr': '1006720', 'oamt': 345.32, 'odt': datetime.datetime(2015, 5, 19, 0, 0), 'inv': '20609400', 'amt': 345.32, 'oodr': '1006720', 'itt': u'\u5916\u4ea4\u90e8', 'ddt': datetime.datetime(2015, 5, 20, 0, 0), 'idt': datetime.datetime(2015, 12, 15, 0, 0)}
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
{'dn': '801097025', 'city': u'BJ', 'cid': '1000218365', 'odr': '1006722', 'oamt': 198.0, 'odt': datetime.datetime(2015, 5, 19, 0, 0), 'inv': '20609400', 'amt': 198.0, 'oodr': '1006722', 'itt': u'\u5916\u4ea4\u90e8', 'ddt': datetime.datetime(2015, 5, 26, 0, 0), 'idt': datetime.datetime(2015, 12, 15, 0, 0)}
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
{'dn': '801085136', 'city': u'BJ', 'cid': '1000218365', 'odr': '1006769', 'oamt': 623.95, 'odt': datetime.datetime(2015, 5, 19, 0, 0), 'inv': '20609400', 'amt': 623.95, 'oodr': '1006769', 'itt': u'\u5916\u4ea4\u90e8', 'ddt': datetime.datetime(2015, 5, 20, 0, 0), 'idt': datetime.datetime(2015, 12, 15, 0, 0)}
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
{'dn': '801085137', 'city': u'BJ', 'cid': '1000218365', 'odr': '1006817', 'oamt': 268.75, 'odt': datetime.datetime(2015, 5, 19, 0, 0), 'inv': '20609400', 'amt': 268.75, 'oodr': '1006817', 'itt': u'\u5916\u4ea4\u90e8', 'ddt': datetime.datetime(2015, 5, 20, 0, 0), 'idt': datetime.datetime(2015, 12, 15, 0, 0)}
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
{'dn': '801085138', 'city': u'BJ', 'cid': '1000218365', 'odr': '1006916', 'oamt': 240.37, 'odt': datetime.datetime(2015, 5, 19, 0, 0), 'inv': '20609400', 'amt': 240.37, 'oodr': '1006916', 'itt': u'\u5916\u4ea4\u90e8', 'ddt': datetime.datetime(2015, 5, 20, 0, 0), 'idt': datetime.datetime(2015, 12, 15, 0, 0)}
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
{'dn': '801085127', 'city': u'BJ', 'cid': '1000218365', 'odr': '1006997', 'oamt': 680.0, 'odt': datetime.datetime(2015, 5, 19, 0, 0), 'inv': '20609400', 'amt': 680.0, 'oodr': '1006997', 'itt': u'\u5916\u4ea4\u90e8', 'ddt': datetime.datetime(2015, 5, 20, 0, 0), 'idt': datetime.datetime(2015, 12, 15, 0, 0)}
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
{'dn': '801085141', 'city': u'BJ', 'cid': '1000218365', 'odr': '1007041', 'oamt': 202.4, 'odt': datetime.datetime(2015, 5, 19, 0, 0), 'inv': '20609400', 'amt': 202.4, 'oodr': '1007041', 'itt': u'\u5916\u4ea4\u90e8', 'ddt': datetime.datetime(2015, 5, 20, 0, 0), 'idt': datetime.datetime(2015, 12, 15, 0, 0)}
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
{'dn': '801085144', 'city': u'BJ', 'cid': '1000218365', 'odr': '1007059', 'oamt': 99.92, 'odt': datetime.datetime(2015, 5, 19, 0, 0), 'inv': '20609400', 'amt': 99.92, 'oodr': '1007059', 'itt': u'\u5916\u4ea4\u90e8', 'ddt': datetime.datetime(2015, 5, 20, 0, 0), 'idt': datetime.datetime(2015, 12, 15, 0, 0)}
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
{'dn': '801085146', 'city': u'BJ', 'cid': '1000218365', 'odr': '1007100', 'oamt': 1142.0, 'odt': datetime.datetime(2015, 5, 19, 0, 0), 'inv': '20609400', 'amt': 1142.0, 'oodr': '1007100', 'itt': u'\u5916\u4ea4\u90e8', 'ddt': datetime.datetime(2015, 5, 20, 0, 0), 'idt': datetime.datetime(2015, 12, 15, 0, 0)}
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
{'dn': '801085150', 'city': u'BJ', 'cid': '1000218365', 'odr': '1007151', 'oamt': 636.1, 'odt': datetime.datetime(2015, 5, 19, 0, 0), 'inv': '20609400', 'amt': 636.1, 'oodr': '1007151', 'itt': u'\u5916\u4ea4\u90e8', 'ddt': datetime.datetime(2015, 5, 20, 0, 0), 'idt': datetime.datetime(2015, 12, 15, 0, 0)}
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
{'dn': '801085151', 'city': u'BJ', 'cid': '1000218365', 'odr': '1007186', 'oamt': 6148.12, 'odt': datetime.datetime(2015, 5, 19, 0, 0), 'inv': '20609400', 'amt': 6148.12, 'oodr': '1007186', 'itt': u'\u5916\u4ea4\u90e8', 'ddt': datetime.datetime(2015, 5, 20, 0, 0), 'idt': datetime.datetime(2015, 12, 15, 0, 0)}
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
{'dn': '801085154', 'city': u'BJ', 'cid': '1000218365', 'odr': '1007233', 'oamt': 1136.4, 'odt': datetime.datetime(2015, 5, 19, 0, 0), 'inv': '20609400', 'amt': 1136.4, 'oodr': '1007233', 'itt': u'\u5916\u4ea4\u90e8', 'ddt': datetime.datetime(2015, 5, 21, 0, 0), 'idt': datetime.datetime(2015, 12, 15, 0, 0)}
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
{'dn': '801085156', 'city': u'BJ', 'cid': '1000218365', 'odr': '1007277', 'oamt': 1822.52, 'odt': datetime.datetime(2015, 5, 19, 0, 0), 'inv': '20609400', 'amt': 1822.52, 'oodr': '1007277', 'itt': u'\u5916\u4ea4\u90e8', 'ddt': datetime.datetime(2015, 5, 21, 0, 0), 'idt': datetime.datetime(2015, 12, 15, 0, 0)}
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
{'dn': '801087572', 'city': u'BJ', 'cid': '1000218365', 'odr': '1009240', 'oamt': 41.6, 'odt': datetime.datetime(2015, 5, 20, 0, 0), 'inv': '20609400', 'amt': 41.6, 'oodr': '1009240', 'itt': u'\u5916\u4ea4\u90e8', 'ddt': datetime.datetime(2015, 5, 21, 0, 0), 'idt': datetime.datetime(2015, 12, 15, 0, 0)}
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
{'dn': '801087573', 'city': u'BJ', 'cid': '1000218365', 'odr': '1009259', 'oamt': 804.0, 'odt': datetime.datetime(2015, 5, 20, 0, 0), 'inv': '20609400', 'amt': 804.0, 'oodr': '1009259', 'itt': u'\u5916\u4ea4\u90e8', 'ddt': datetime.datetime(2015, 5, 21, 0, 0), 'idt': datetime.datetime(2015, 12, 15, 0, 0)}
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
{'dn': '801087574', 'city': u'BJ', 'cid': '1000218365', 'odr': '1009268', 'oamt': 246.9, 'odt': datetime.datetime(2015, 5, 20, 0, 0), 'inv': '20609400', 'amt': 246.9, 'oodr': '1009268', 'itt': u'\u5916\u4ea4\u90e8', 'ddt': datetime.datetime(2015, 5, 21, 0, 0), 'idt': datetime.datetime(2015, 12, 15, 0, 0)}
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
{'dn': '801088622', 'city': u'NBJ', 'cid': '1000276761', 'odr': '1009888', 'oamt': 666.0, 'odt': datetime.datetime(2015, 5, 20, 0, 0), 'inv': '5436727', 'amt': 126.0, 'oodr': '1009888', 'itt': u'\u4e2d\u56fd\u79d1\u5b66\u9662\u5fae\u7535\u5b50\u7814\u7a76\u6240', 'ddt': datetime.datetime(2015, 5, 22, 0, 0), 'idt': datetime.datetime(2016, 12, 28, 0, 0)}
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
{'dn': '801088622', 'city': u'NBJ', 'cid': '1000276761', 'odr': '1009888', 'oamt': 666.0, 'odt': datetime.datetime(2015, 5, 20, 0, 0), 'inv': '5436728', 'amt': 540.0, 'oodr': '1009888', 'itt': u'\u4e2d\u56fd\u79d1\u5b66\u9662\u5fae\u7535\u5b50\u7814\u7a76\u6240', 'ddt': datetime.datetime(2015, 5, 22, 0, 0), 'idt': datetime.datetime(2016, 12, 28, 0, 0)}
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
{'dn': '801088322', 'city': u'BJ', 'cid': '1000218365', 'odr': '1009956', 'oamt': 163.68, 'odt': datetime.datetime(2015, 5, 20, 0, 0), 'inv': '20609400', 'amt': 163.68, 'oodr': '1009956', 'itt': u'\u5916\u4ea4\u90e8', 'ddt': datetime.datetime(2015, 5, 21, 0, 0), 'idt': datetime.datetime(2015, 12, 15, 0, 0)}
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
{'dn': '801089913', 'city': u'BJ', 'cid': '1000236974', 'odr': '1011092', 'oamt': 185.0, 'odt': datetime.datetime(2015, 5, 21, 0, 0), 'inv': '9136762', 'amt': 185.0, 'oodr': '1011092', 'itt': u'\u6d77\u6dc0\u533a\u516b\u91cc\u5e84\u8857\u9053\u529e\u4e8b\u5904', 'ddt': datetime.datetime(2015, 5, 22, 0, 0), 'idt': datetime.datetime(2015, 8, 5, 0, 0)}
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
{'dn': '801100336', 'city': u'BJ', 'cid': '1000218365', 'odr': '1021331', 'oamt': 42.0, 'odt': datetime.datetime(2015, 5, 26, 0, 0), 'inv': '20609400', 'amt': 42.0, 'oodr': '1021331', 'itt': u'\u5916\u4ea4\u90e8', 'ddt': datetime.datetime(2015, 5, 27, 0, 0), 'idt': datetime.datetime(2015, 12, 15, 0, 0)}
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
{'dn': '801102219', 'city': u'BJ', 'cid': '1000218365', 'odr': '1022420', 'oamt': 74.0, 'odt': datetime.datetime(2015, 5, 27, 0, 0), 'inv': '20609400', 'amt': 74.0, 'oodr': '1022420', 'itt': u'\u5916\u4ea4\u90e8', 'ddt': datetime.datetime(2015, 5, 28, 0, 0), 'idt': datetime.datetime(2015, 12, 15, 0, 0)}
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
{'dn': '801102223', 'city': u'BJ', 'cid': '1000218365', 'odr': '1022464', 'oamt': 7537.0, 'odt': datetime.datetime(2015, 5, 27, 0, 0), 'inv': '20609400', 'amt': 7537.0, 'oodr': '1022464', 'itt': u'\u5916\u4ea4\u90e8', 'ddt': datetime.datetime(2015, 5, 28, 0, 0), 'idt': datetime.datetime(2015, 12, 15, 0, 0)}
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
{'dn': '801102224', 'city': u'BJ', 'cid': '1000218365', 'odr': '1022469', 'oamt': 40.0, 'odt': datetime.datetime(2015, 5, 27, 0, 0), 'inv': '20609400', 'amt': 40.0, 'oodr': '1022469', 'itt': u'\u5916\u4ea4\u90e8', 'ddt': datetime.datetime(2015, 5, 28, 0, 0), 'idt': datetime.datetime(2015, 12, 15, 0, 0)}
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
{'dn': '801102225', 'city': u'BJ', 'cid': '1000218365', 'odr': '1022500', 'oamt': 330.0, 'odt': datetime.datetime(2015, 5, 27, 0, 0), 'inv': '20609400', 'amt': 330.0, 'oodr': '1022500', 'itt': u'\u5916\u4ea4\u90e8', 'ddt': datetime.datetime(2015, 5, 28, 0, 0), 'idt': datetime.datetime(2015, 12, 15, 0, 0)}
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
{'dn': '801102226', 'city': u'BJ', 'cid': '1000218365', 'odr': '1022525', 'oamt': 552.92, 'odt': datetime.datetime(2015, 5, 27, 0, 0), 'inv': '20609400', 'amt': 552.92, 'oodr': '1022525', 'itt': u'\u5916\u4ea4\u90e8', 'ddt': datetime.datetime(2015, 5, 28, 0, 0), 'idt': datetime.datetime(2015, 12, 15, 0, 0)}
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
{'dn': '801102230', 'city': u'BJ', 'cid': '1000218365', 'odr': '1022553', 'oamt': 2743.51, 'odt': datetime.datetime(2015, 5, 27, 0, 0), 'inv': '20609400', 'amt': 2743.51, 'oodr': '1022553', 'itt': u'\u5916\u4ea4\u90e8', 'ddt': datetime.datetime(2015, 5, 28, 0, 0), 'idt': datetime.datetime(2015, 12, 15, 0, 0)}
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
{'dn': '801102231', 'city': u'BJ', 'cid': '1000218365', 'odr': '1022557', 'oamt': 58.0, 'odt': datetime.datetime(2015, 5, 27, 0, 0), 'inv': '20609400', 'amt': 40.0, 'oodr': '1022557', 'itt': u'\u5916\u4ea4\u90e8', 'ddt': datetime.datetime(2015, 5, 28, 0, 0), 'idt': datetime.datetime(2015, 12, 15, 0, 0)}
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
{'dn': '801103636', 'city': u'BJ', 'cid': '1000218365', 'odr': '1022557', 'oamt': 58.0, 'odt': datetime.datetime(2015, 5, 27, 0, 0), 'inv': '20609400', 'amt': 18.0, 'oodr': '1022557', 'itt': u'\u5916\u4ea4\u90e8', 'ddt': datetime.datetime(2015, 5, 28, 0, 0), 'idt': datetime.datetime(2015, 12, 15, 0, 0)}
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
{'dn': '801102979', 'city': u'BJ', 'cid': '1000218365', 'odr': '1022571', 'oamt': 315.0, 'odt': datetime.datetime(2015, 5, 27, 0, 0), 'inv': '20609400', 'amt': 315.0, 'oodr': '1022571', 'itt': u'\u5916\u4ea4\u90e8', 'ddt': datetime.datetime(2015, 5, 28, 0, 0), 'idt': datetime.datetime(2015, 12, 15, 0, 0)}
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
{'dn': '801102980', 'city': u'BJ', 'cid': '1000218365', 'odr': '1022685', 'oamt': 1058.0, 'odt': datetime.datetime(2015, 5, 27, 0, 0), 'inv': '20609400', 'amt': 1058.0, 'oodr': '1022685', 'itt': u'\u5916\u4ea4\u90e8', 'ddt': datetime.datetime(2015, 5, 28, 0, 0), 'idt': datetime.datetime(2015, 12, 15, 0, 0)}
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
{'dn': '801102981', 'city': u'BJ', 'cid': '1000218365', 'odr': '1022718', 'oamt': 859.2, 'odt': datetime.datetime(2015, 5, 27, 0, 0), 'inv': '20609400', 'amt': 859.2, 'oodr': '1022718', 'itt': u'\u5916\u4ea4\u90e8', 'ddt': datetime.datetime(2015, 5, 28, 0, 0), 'idt': datetime.datetime(2015, 12, 15, 0, 0)}
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
{'dn': '801102245', 'city': u'BJ', 'cid': '1000218365', 'odr': '1022729', 'oamt': 160.0, 'odt': datetime.datetime(2015, 5, 27, 0, 0), 'inv': '20609400', 'amt': 160.0, 'oodr': '1022729', 'itt': u'\u5916\u4ea4\u90e8', 'ddt': datetime.datetime(2015, 5, 28, 0, 0), 'idt': datetime.datetime(2015, 12, 15, 0, 0)}
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
{'dn': '801103469', 'city': u'BJ', 'cid': '1000218365', 'odr': '1023799', 'oamt': 1433.4, 'odt': datetime.datetime(2015, 5, 27, 0, 0), 'inv': '20609400', 'amt': 1433.4, 'oodr': '1023799', 'itt': u'\u5916\u4ea4\u90e8', 'ddt': datetime.datetime(2015, 5, 28, 0, 0), 'idt': datetime.datetime(2015, 12, 15, 0, 0)}
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
{'dn': '801102879', 'city': u'SH', 'cid': '1000232196', 'odr': '1023846', 'oamt': 343.0, 'odt': datetime.datetime(2015, 5, 27, 0, 0), 'inv': '15478163', 'amt': 0.0, 'oodr': '1023846', 'itt': u'\u56fd\u7f51\u5317\u4eac\u5e02\u7535\u529b\u516c\u53f8', 'ddt': datetime.datetime(2015, 5, 28, 0, 0), 'idt': datetime.datetime(2015, 8, 17, 0, 0)}
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
{'dn': '801102879', 'city': u'SH', 'cid': '1000232196', 'odr': '1023846', 'oamt': 343.0, 'odt': datetime.datetime(2015, 5, 27, 0, 0), 'inv': '15486002', 'amt': 47.64, 'oodr': '1023846', 'itt': u'\u56fd\u7f51\u5317\u4eac\u5e02\u7535\u529b\u516c\u53f8', 'ddt': datetime.datetime(2015, 5, 28, 0, 0), 'idt': datetime.datetime(2015, 9, 10, 0, 0)}
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.NaTType'>
<class 'pandas.tslib.Timestamp'>
{'dn': '801104041', 'city': u'SH', 'cid': '1000419959', 'odr': '1024652', 'oamt': 29556.24, 'odt': datetime.datetime(2015, 5, 27, 0, 0), 'inv': '15486305', 'amt': 28080.04, 'oodr': '1024652', 'itt': u'\u6210\u90fd\u8d1d\u8a89\u79d1\u6280\u6709\u9650\u516c\u53f8', 'ddt': NaT, 'idt': datetime.datetime(2015, 9, 11, 0, 0)}
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
{'dn': '801104043', 'city': u'BJ', 'cid': '1000243808', 'odr': '1024744', 'oamt': 579.0, 'odt': datetime.datetime(2015, 5, 28, 0, 0), 'inv': '2924633', 'amt': 579.0, 'oodr': '1024744', 'itt': u'\u5929\u6d25\u4ebf\u4e07\u534e\u6e38\u8247\u8d38\u6613\u6709\u9650\u516c\u53f8', 'ddt': datetime.datetime(2015, 5, 29, 0, 0), 'idt': datetime.datetime(2015, 6, 12, 0, 0)}
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>
<class 'pandas.tslib.Timestamp'>